### ISSUE TITLE
Request for Zero Shot Point Cloud Segmentation by Semantic Visual Aware Synthesis Source Code Release Date

### ISSUE THREAD

**Issue by Rickilous** [leolyj/3DPC-GZSL#1]
Dear leolyj,

I hope this message finds you well. I am a beginner in 3D point cloud semantic segmentation, and I have been studying your team’s paper on Zero Shot Point Cloud Segmentation by Semantic Visual Aware Synthesis. I am very impressed by your progress and achievements in this field, and I would like to express my admiration for your work.

However, I have encountered some difficulties while studying your paper, and I was wondering if you could kindly provide me with an update on when your team plans to release the source code for this project. I would be very grateful for any information you could share with me.

Thank you very much for your time and consideration.

Best regards, Rickilous

**Comment by yuwei138** [comment]
Thanks for your attention and interest in our work! We will release our code and model around mid-November. We are now sorting our code, which may take a little time. We'll let you know as soon as the code becomes public. Best wishes!

**Comment by Rickilous** [comment]
Thank you for sharing! I am surprised and honored that you were able to reply to me so quickly. I am excited to hear that you will be releasing your code soon. I appreciate your hard work and dedication , and wish you all the best in your future work!😄😄😄

**Comment by yuwei138** [comment]
@Rickilous Hi, Rickilous, Sorry for the delay, the release of the code has been postponed recently due to the other paper deadline, there is our newly to-do list:

1. We will release our training and test code before December 17th, 2023; (As soon as We can)
2. We will release our pretrained model within December;

Thanks for your patient! And sorry for our busy work. Best regards!

**Comment by IzhiSu** [comment]
Thanks to the author's beautiful work. Looking forward to open source!
